<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj/**;bin/**;StrykerOutput/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
