using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Genix.Areas;
using Genix.Assets;
using Genix.Core;
using Genix.Editor.Drawers;
using Genix.Editor.Infrastructure;
using Genix.Editor.TargetAreas;
using Genix.Editor.DevTools;
using Genix.Editor.UI;
using Genix.Editor.Utilities;
using Genix.Styles;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Genix.Editor.Benchmarking
{
    /// <summary>Configures, runs, and inspects reproducible Genix performance benchmark campaigns.</summary>
    public sealed class GenerationBenchmarkWindow : EditorWindow
    {
        private const string SelectedSuiteKey = "Genix.Benchmarks.SelectedSuite";

        private GenerationBenchmarkSuite _suite;
        private SerializedObject _serializedSuite;
        private int _selectedScenario;
        private Vector2 _scenarioScroll;
        private Vector2 _detailsScroll;
        private Vector2 _resultsScroll;
        private bool _showCampaignSettings;
        private bool _showSurfaceSearchSettings;
        private bool _showDistributionSettings;
        private bool _showProximitySettings;
        private string _validationMessage = string.Empty;
        private MessageType _validationMessageType = MessageType.None;

        private AssetPool[] _assetPools = Array.Empty<AssetPool>();
        private string[] _assetPoolOptions = Array.Empty<string>();
        private StylePreset[] _stylePresets = Array.Empty<StylePreset>();
        private string[] _stylePresetOptions = Array.Empty<string>();
        private GenerationBenchmarkSuite[] _benchmarkSuites = Array.Empty<GenerationBenchmarkSuite>();
        private string[] _benchmarkSuiteOptions = Array.Empty<string>();

        private static readonly RelativePlacementSource[] BenchmarkRelativeSources =
        {
            RelativePlacementSource.None,
            RelativePlacementSource.Any,
            RelativePlacementSource.GeneratedObjects,
            RelativePlacementSource.SceneObjects
        };

        private static readonly GUIContent[] BenchmarkRelativeSourceOptions =
        {
            new("None", "Do not constrain placements relative to other objects."),
            new("Generated + Scene Objects", "Keep placements near generated objects or matching scene objects."),
            new("Generated Objects", "Keep new placements near objects already planned or generated by Genix."),
            new("Scene Objects", "Keep placements near existing scene objects on the selected layers.")
        };

        [MenuItem("Tools/Genix Developer/Benchmarks", false, 20)]
        public static void Open()
        {
            GenerationBenchmarkWindow window = GenixWindowDocking.Open<GenerationBenchmarkWindow>("Genix Benchmarks");
            window.minSize = new Vector2(760f, 520f);
        }

        private void OnEnable()
        {
            GenerationBenchmarkRunner.Changed += Repaint;
            EditorApplication.projectChanged += HandleProjectChanged;
            string suiteGuid = EditorPrefs.GetString(SelectedSuiteKey, string.Empty);
            string path = AssetDatabase.GUIDToAssetPath(suiteGuid);
            GenerationBenchmarkSuite rememberedSuite = AssetDatabase.LoadAssetAtPath<GenerationBenchmarkSuite>(path);
            RefreshSelectableAssets();
            SetSuite(rememberedSuite ? rememberedSuite : _benchmarkSuites.FirstOrDefault());
        }

        private void OnDisable()
        {
            GenerationBenchmarkRunner.Changed -= Repaint;
            EditorApplication.projectChanged -= HandleProjectChanged;
        }

        private void OnGUI()
        {
            DrawToolbar();
            EditorGUILayout.Space(4f);

            if (!_suite)
                return;

            EnsureSerializedSuite();
            DrawRunPanel();
            EditorGUILayout.Space(5f);

            using (new EditorGUILayout.HorizontalScope())
            {
                DrawScenarioList();
                GUILayout.Space(6f);
                DrawScenarioDetails();
            }

            DrawResults();
            _serializedSuite.ApplyModifiedProperties();
        }

        private void DrawToolbar()
        {
            using (new EditorGUILayout.HorizontalScope(EditorStyles.toolbar))
            {
                DrawSuiteDropdown();

                if (GUILayout.Button(
                        new GUIContent("Create", "Create and select a new benchmark suite."),
                        EditorStyles.toolbarButton,
                        GUILayout.Width(56f)))
                {
                    CreateSuite();
                }

                GUILayout.FlexibleSpace();

                using (new EditorGUI.DisabledScope(string.IsNullOrWhiteSpace(GenerationBenchmarkRunner.LastOutputDirectory)))
                {
                    if (GUILayout.Button("Results", EditorStyles.toolbarButton, GUILayout.Width(62f)))
                        EditorUtility.RevealInFinder(GenerationBenchmarkRunner.LastOutputDirectory);
                }
            }
        }

        private void DrawSuiteDropdown()
        {
            if (_benchmarkSuites.Length == 0)
            {
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.Popup(
                        0,
                        new[] { "No Benchmark Suites" },
                        EditorStyles.toolbarPopup,
                        GUILayout.MinWidth(220f),
                        GUILayout.MaxWidth(420f));
                }
                return;
            }

            int selectedIndex = Array.IndexOf(_benchmarkSuites, _suite);
            if (selectedIndex < 0)
                selectedIndex = 0;

            EditorGUI.BeginChangeCheck();
            selectedIndex = EditorGUILayout.Popup(
                selectedIndex,
                _benchmarkSuiteOptions,
                EditorStyles.toolbarPopup,
                GUILayout.MinWidth(220f),
                GUILayout.MaxWidth(420f));
            if (EditorGUI.EndChangeCheck())
                SetSuite(_benchmarkSuites[Mathf.Clamp(selectedIndex, 0, _benchmarkSuites.Length - 1)]);
        }

        private void DrawRunPanel()
        {
            if (DeveloperWindowUi.SectionHeader(
                    new GUIContent("Campaign", "Run and validate the configured benchmark campaign."),
                    new GUIContent("Validate", "Check the suite without running it."),
                    !GenerationBenchmarkRunner.IsRunning,
                    72f))
            {
                ValidateSuite();
            }

            using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
            {
                using (new EditorGUILayout.HorizontalScope())
                {
                    using (new EditorGUI.DisabledScope(GenerationBenchmarkRunner.IsRunning))
                    {
                        if (DeveloperWindowUi.CommandButton(new GUIContent("Run Full Suite"), 0, 2, 120f))
                            StartBenchmark(selectedOnly: false);

                        if (DeveloperWindowUi.CommandButton(new GUIContent("Run Selected"), 1, 2, 120f))
                            StartBenchmark(selectedOnly: true);
                    }

                    using (new EditorGUI.DisabledScope(!GenerationBenchmarkRunner.IsRunning))
                    {
                        if (GUILayout.Button("Stop", EditorStyles.miniButton, GUILayout.Height(28f), GUILayout.Width(70f)))
                            GenerationBenchmarkRunner.RequestStop();
                    }

                    GUILayout.FlexibleSpace();
                    DrawGlobalSettings();
                }

                float progress = GenerationBenchmarkRunner.TotalRuns > 0
                    ? GenerationBenchmarkRunner.CompletedRuns / (float)GenerationBenchmarkRunner.TotalRuns
                    : 0f;
                string progressLabel = GenerationBenchmarkRunner.IsRunning
                    ? $"{GenerationBenchmarkRunner.Status} | elapsed {FormatDuration(GenerationBenchmarkRunner.ElapsedSeconds)} | ETA {FormatDuration(GenerationBenchmarkRunner.EstimatedRemainingSeconds)}"
                    : GenerationBenchmarkRunner.Status;
                EditorGUI.ProgressBar(EditorGUILayout.GetControlRect(false, 19f), progress, progressLabel);

                if (!string.IsNullOrWhiteSpace(_validationMessage) &&
                    _validationMessageType is MessageType.Warning or MessageType.Error)
                    EditorGUILayout.HelpBox(_validationMessage, _validationMessageType);
                if (!string.IsNullOrWhiteSpace(GenerationBenchmarkRunner.LastError))
                    EditorGUILayout.HelpBox(GenerationBenchmarkRunner.LastError, MessageType.Error);

                _showCampaignSettings = EditorGUILayout.Foldout(
                    _showCampaignSettings,
                    "Campaign Settings",
                    true);

                if (_showCampaignSettings)
                    DrawCampaignSettings();
            }
        }

        private void DrawGlobalSettings()
        {
            SerializedProperty cache = _serializedSuite.FindProperty("cacheConditions");
            SerializedProperty measurements = _serializedSuite.FindProperty("measurements");
            EditorGUILayout.PropertyField(cache, GUIContent.none, GUILayout.Width(115f));
            EditorGUILayout.PropertyField(measurements, GUIContent.none, GUILayout.Width(150f));
        }

        private void DrawCampaignSettings()
        {
            using (new EditorGUI.DisabledScope(GenerationBenchmarkRunner.IsRunning))
            {
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("coldSeedCount"),
                    new GUIContent("Cold Seeds", "Measured seeds per object count with all Genix data caches cleared before every sample."));
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("warmSeedCount"),
                    new GUIContent("Warm Seeds", "Measured seeds per object count after an unmeasured cache warm-up."));
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("warmupRuns"),
                    new GUIContent("Code Warm-ups", "Unmeasured executions per block. Cold caches are cleared again after these runs."));
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("repetitions"),
                    new GUIContent("Repetitions", "Repeated measurements per seed. Keep at one when many independent seeds are used."));
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("settleFrames"),
                    new GUIContent("Scene Settle Frames", "Editor frames excluded from timing after opening each scene."));
                EditorGUILayout.PropertyField(
                    _serializedSuite.FindProperty("seeds"),
                    new GUIContent("Deterministic Seeds"),
                    true);
            }
        }

        private void DrawScenarioList()
        {
            SerializedProperty scenarios = _serializedSuite.FindProperty("scenarios");

            float listWidth = DeveloperWindowUi.ResponsiveListWidth(position.width, 240f, 500f);
            using (new EditorGUILayout.VerticalScope(GUILayout.Width(listWidth)))
            {
                EditorGUILayout.LabelField("Scenarios", EditorStyles.boldLabel);
                _scenarioScroll = EditorGUILayout.BeginScrollView(_scenarioScroll, EditorStyles.helpBox);

                for (int i = 0; i < scenarios.arraySize; i++)
                {
                    SerializedProperty scenario = scenarios.GetArrayElementAtIndex(i);
                    string name = scenario.FindPropertyRelative("displayName").stringValue;
                    bool enabled = scenario.FindPropertyRelative("enabled").boolValue;
                    string label = enabled ? name : $"{name} (Excluded)";

                    if (DeveloperWindowUi.SelectableRow(
                            i == _selectedScenario,
                            new GUIContent(label, enabled ? "Included in the benchmark suite." : "Excluded from the benchmark suite."),
                            24f,
                            listWidth - 20f))
                        _selectedScenario = i;
                }

                EditorGUILayout.EndScrollView();

                using (new EditorGUILayout.HorizontalScope())
                {
                    using (new EditorGUI.DisabledScope(GenerationBenchmarkRunner.IsRunning))
                    {
                        if (GUILayout.Button("+"))
                        {
                            _serializedSuite.ApplyModifiedProperties();
                            Undo.RecordObject(_suite, "Added Benchmark Scenario");
                            _suite.AddScenario("Benchmark Scenario", null);
                            EditorUtility.SetDirty(_suite);
                            _selectedScenario = _suite.Scenarios.Count - 1;
                            EnsureSerializedSuite(force: true);
                        }

                        using (new EditorGUI.DisabledScope(scenarios.arraySize == 0))
                        {
                            if (GUILayout.Button("-"))
                            {
                                _serializedSuite.ApplyModifiedProperties();
                                Undo.RecordObject(_suite, "Removed Benchmark Scenario");
                                _suite.RemoveScenarioAt(_selectedScenario);
                                EditorUtility.SetDirty(_suite);
                                _selectedScenario = Mathf.Clamp(_selectedScenario, 0, Mathf.Max(0, _suite.Scenarios.Count - 1));
                                EnsureSerializedSuite(force: true);
                            }
                        }
                    }
                }
            }
        }

        private void DrawScenarioDetails()
        {
            SerializedProperty scenarios = _serializedSuite.FindProperty("scenarios");

            using (new EditorGUILayout.VerticalScope(GUILayout.ExpandWidth(true)))
            {
                EditorGUILayout.LabelField("Configuration", EditorStyles.boldLabel);
                _detailsScroll = EditorGUILayout.BeginScrollView(_detailsScroll, EditorStyles.helpBox);

                if (scenarios.arraySize == 0)
                {
                    EditorGUILayout.EndScrollView();
                    return;
                }

                _selectedScenario = Mathf.Clamp(_selectedScenario, 0, scenarios.arraySize - 1);
                SerializedProperty scenario = scenarios.GetArrayElementAtIndex(_selectedScenario);

                float previousLabelWidth = EditorGUIUtility.labelWidth;
                float detailsWidth = Mathf.Max(
                    390f,
                    position.width - DeveloperWindowUi.ResponsiveListWidth(position.width, 240f, 500f) - 30f);
                EditorGUIUtility.labelWidth = Mathf.Clamp(detailsWidth * 0.38f, 170f, 220f);

                try
                {
                    using (new EditorGUI.DisabledScope(GenerationBenchmarkRunner.IsRunning))
                        DrawScenarioConfiguration(scenario);
                }
                finally
                {
                    EditorGUIUtility.labelWidth = previousLabelWidth;
                }

                EditorGUILayout.EndScrollView();
            }
        }

        private void DrawScenarioConfiguration(SerializedProperty scenario)
        {
            EditorGUILayout.PropertyField(
                scenario.FindPropertyRelative("enabled"),
                new GUIContent("Include in Suite", "Run this scenario as part of the full benchmark suite."));
            EditorGUILayout.PropertyField(scenario.FindPropertyRelative("displayName"), new GUIContent("Name"));
            EditorGUILayout.PropertyField(scenario.FindPropertyRelative("scene"), new GUIContent("Scene"));
            DrawTargetFields(scenario);

            EditorGUILayout.Space(7f);
            EditorGUILayout.LabelField("Generation", EditorStyles.boldLabel);
            DrawAssetSelectors(scenario);
            DrawPlacementTargets(scenario.FindPropertyRelative("placementTargets"));
            EditorGUILayout.PropertyField(
                scenario.FindPropertyRelative("bestEffort"),
                new GUIContent("Allow Partial Results", "Keep valid placements when Genix cannot reach the requested count. Disable to require a complete result."));
            EditorGUILayout.PropertyField(
                scenario.FindPropertyRelative("objectCounts"),
                new GUIContent("Object Counts", "Requested object counts measured as separate benchmark cases."),
                true);

            EditorGUILayout.Space(10f);
            EditorGUILayout.LabelField("Advanced Settings", EditorStyles.boldLabel);
            DrawAdvancedScenarioSettings(scenario);
        }

        private void DrawAssetSelectors(SerializedProperty scenario)
        {
            SerializedProperty assetPoolProperty = scenario.FindPropertyRelative("assetPool");
            AssetPool selectedPool = assetPoolProperty.objectReferenceValue as AssetPool;
            AssetPool newPool = AssetDropdown.DrawAssetPoolDropdownWithEditButton(
                new GUIContent(
                    "Asset Pool",
                    "Choose which assets Genix may place. Manual pools use an explicit list; rule-based pools find matching catalog assets."),
                _assetPools,
                _assetPoolOptions,
                selectedPool);
            if (newPool != selectedPool)
                assetPoolProperty.objectReferenceValue = newPool;

            SerializedProperty styleProperty = scenario.FindPropertyRelative("stylePreset");
            StylePreset selectedStyle = styleProperty.objectReferenceValue as StylePreset;
            StylePreset newStyle = AssetDropdown.DrawStylePresetDropdownWithEditButton(
                CreateGenerationStyleLabel(selectedStyle),
                _stylePresets,
                _stylePresetOptions,
                selectedStyle);
            if (newStyle != selectedStyle)
                styleProperty.objectReferenceValue = newStyle;
        }

        private static GUIContent CreateGenerationStyleLabel(StylePreset style)
        {
            const string guidance = "Choose the overall spacing and distribution behavior for this run.";
            string description = style ? style.Settings.description : string.Empty;
            string tooltip = string.IsNullOrWhiteSpace(description)
                ? guidance
                : $"{guidance}\n\n{style.name}: {description}";
            return new GUIContent("Generation Style", tooltip);
        }

        private void DrawPlacementTargets(SerializedProperty targetsProperty)
        {
            PlacementTarget targets = PlacementTargetSelectionField.Normalize((PlacementTarget)targetsProperty.intValue);
            targetsProperty.intValue = (int)targets;

            Rect controlRect = EditorGUILayout.GetControlRect();
            Rect dropdownRect = EditorGUI.PrefixLabel(
                controlRect,
                new GUIContent("Placement Targets", "Choose the surface and volume types Genix may use. Assets must support a selected target."));
            string selectionLabel = PlacementTargetSelectionField.GetLabel(targets, "Select Target");

            if (!EditorGUI.DropdownButton(
                    dropdownRect,
                    new GUIContent(selectionLabel, selectionLabel),
                    FocusType.Keyboard,
                    EditorGui.EllipsizedPopupStyle))
                return;

            PlacementTargetSelectionField.Show(
                dropdownRect,
                targets,
                updatedTargets =>
                {
                    targetsProperty.intValue = (int)PlacementTargetSelectionField.Normalize(updatedTargets);
                    targetsProperty.serializedObject.ApplyModifiedProperties();
                    Repaint();
                },
                "Disable every placement target. The scenario remains invalid until at least one target is selected.",
                "Allow Floor, Wall, Ceiling, and Inside Space assets in the same run.");
        }

        private void DrawAdvancedScenarioSettings(SerializedProperty scenario)
        {
            SerializedProperty targetsProperty = scenario.FindPropertyRelative("placementTargets");
            PlacementTarget targets = PlacementTargetSelectionField.Normalize((PlacementTarget)targetsProperty.intValue);

            _showSurfaceSearchSettings = EditorGUILayout.BeginFoldoutHeaderGroup(
                _showSurfaceSearchSettings,
                new GUIContent("Surface Search", "Control where Genix looks for floors, walls, and ceilings."));
            if (_showSurfaceSearchSettings)
            {
                EditorGUI.indentLevel++;
                DrawSurfaceSearchSettings(scenario.FindPropertyRelative("areaBuildSettings"), targets);
                EditorGUI.indentLevel--;
            }
            EditorGUILayout.EndFoldoutHeaderGroup();

            if (GetSelectedTargetCount(targets) > 1)
            {
                _showDistributionSettings = EditorGUILayout.BeginFoldoutHeaderGroup(
                    _showDistributionSettings,
                    new GUIContent("Distribution", "Control how placements are divided across placement targets."));
                if (_showDistributionSettings)
                {
                    EditorGUI.indentLevel++;
                    DrawTargetDistribution(scenario, targets);
                    EditorGUI.indentLevel--;
                }
                EditorGUILayout.EndFoldoutHeaderGroup();
            }
            else
            {
                scenario.FindPropertyRelative("targetDistributionMode").intValue = (int)TargetDistributionMode.Random;
            }

            _showProximitySettings = EditorGUILayout.BeginFoldoutHeaderGroup(
                _showProximitySettings,
                new GUIContent("Global Proximity", "Keep every generated placement near an eligible scene or generated object."));
            if (_showProximitySettings)
            {
                EditorGUI.indentLevel++;
                DrawRelativePlacement(scenario.FindPropertyRelative("relativePlacement"));
                EditorGUI.indentLevel--;
            }
            EditorGUILayout.EndFoldoutHeaderGroup();
        }

        private void DrawTargetFields(SerializedProperty scenario)
        {
            SerializedProperty sceneProperty = scenario.FindPropertyRelative("scene");
            SerializedProperty providerProperty = scenario.FindPropertyRelative("areaProviderId");
            SerializedProperty targetProperty = scenario.FindPropertyRelative("targetId");
            IReadOnlyList<IBenchmarkAreaResolver> resolvers = BenchmarkAreaResolverRegistry.CreateResolvers();

            if (resolvers.Count == 0)
            {
                EditorGUILayout.HelpBox("No benchmark target provider is installed.", MessageType.Error);
                return;
            }

            int providerIndex = resolvers.ToList().FindIndex(resolver => resolver.ProviderId == providerProperty.stringValue);
            if (providerIndex < 0)
                providerIndex = 0;

            if (resolvers.Count > 1)
            {
                int newIndex = EditorGui.Popup(
                    new GUIContent("Area Provider", "Spatial integration used to resolve the target after each scene switch."),
                    providerIndex,
                    resolvers.Select(resolver => resolver.DisplayName).ToArray());
                providerIndex = Mathf.Clamp(newIndex, 0, resolvers.Count - 1);
            }

            providerProperty.stringValue = resolvers[providerIndex].ProviderId;

            SceneAsset sceneAsset = sceneProperty.objectReferenceValue as SceneAsset;
            string scenePath = sceneAsset ? AssetDatabase.GetAssetPath(sceneAsset) : string.Empty;
            Scene activeScene = SceneManager.GetActiveScene();

            if (sceneAsset && string.Equals(activeScene.path, scenePath, StringComparison.Ordinal))
            {
                IBenchmarkAreaResolver resolver = resolvers[providerIndex];
                IReadOnlyList<BenchmarkAreaTarget> targets = resolver?.FindTargets(activeScene) ?? Array.Empty<BenchmarkAreaTarget>();

                if (targets.Count > 0)
                {
                    int targetIndex = targets.ToList().FindIndex(target => target.Id == targetProperty.stringValue);
                    if (targetIndex < 0)
                        targetIndex = 0;
                    int newTargetIndex = EditorGui.Popup(
                        new GUIContent("Target Area", "Area used for every automated run of this scenario."),
                        targetIndex,
                        targets.Select(target => target.DisplayName).ToArray());
                    targetProperty.stringValue = targets[Mathf.Clamp(newTargetIndex, 0, targets.Count - 1)].Id;
                    return;
                }

                EditorGUILayout.HelpBox("No target areas were found in the selected scene.", MessageType.Warning);
                return;
            }

            string status = !sceneAsset
                ? "Select a scene first"
                : string.IsNullOrWhiteSpace(targetProperty.stringValue)
                    ? "Open scene to select"
                    : "Saved in scene";
            using (new EditorGUI.DisabledScope(true))
            {
                EditorGUILayout.TextField(
                    new GUIContent(
                        "Target Area",
                        "The saved target is resolved automatically after the benchmark opens this scene. " +
                        "Open the scene to change the target."),
                    status);
            }
        }

        private static void DrawSurfaceSearchSettings(SerializedProperty settings, PlacementTarget targets)
        {
            SerializedProperty discoveryProperty = settings.FindPropertyRelative("surfaceDiscoveryMode");
            SurfaceDiscoveryMode discoveryMode = (SurfaceDiscoveryMode)discoveryProperty.intValue;
            int discoveryIndex = Array.IndexOf(GenerationConfigurationOptions.SurfaceDiscoveryModes, discoveryMode);
            if (discoveryIndex < 0)
                discoveryIndex = 0;

            discoveryIndex = EditorGui.Popup(
                new GUIContent("Surface Search Mode", "Choose how Genix finds floor, wall, and ceiling candidates."),
                discoveryIndex,
                GenerationConfigurationOptions.SurfaceDiscoveryLabels);
            discoveryMode = GenerationConfigurationOptions.SurfaceDiscoveryModes[
                Mathf.Clamp(discoveryIndex, 0, GenerationConfigurationOptions.SurfaceDiscoveryModes.Length - 1)];
            discoveryProperty.intValue = (int)discoveryMode;

            if (discoveryMode != SurfaceDiscoveryMode.AllMatchingSurfacesInVolume &&
                (targets & (PlacementTarget.Floor | PlacementTarget.Ceiling)) != 0)
            {
                SerializedProperty decompositionProperty = settings.FindPropertyRelative("decompositionMode");
                AreaDecompositionMode decompositionMode = (AreaDecompositionMode)decompositionProperty.intValue;
                int decompositionIndex = Array.IndexOf(GenerationConfigurationOptions.AreaDecompositionModes, decompositionMode);
                if (decompositionIndex < 0)
                    decompositionIndex = 0;

                decompositionIndex = EditorGui.Popup(
                    new GUIContent("Voxel Boundary Detail", "Choose how closely floor and ceiling regions preserve irregular voxel boundaries."),
                    decompositionIndex,
                    GenerationConfigurationOptions.AreaDecompositionLabels);
                decompositionProperty.intValue = (int)GenerationConfigurationOptions.AreaDecompositionModes[
                    Mathf.Clamp(decompositionIndex, 0, GenerationConfigurationOptions.AreaDecompositionModes.Length - 1)];
            }

            if (discoveryMode == SurfaceDiscoveryMode.SfsBoundaries)
                return;

            SerializedProperty floorLayers = settings.FindPropertyRelative("floorSurfaceLayers");
            SerializedProperty wallLayers = settings.FindPropertyRelative("wallSurfaceLayers");
            SerializedProperty ceilingLayers = settings.FindPropertyRelative("ceilingSurfaceLayers");
            EditorGUILayout.PropertyField(
                floorLayers,
                new GUIContent("Floor Layers", "Use upward-facing colliders on these layers as floors."));
            EditorGUILayout.PropertyField(
                wallLayers,
                new GUIContent("Wall Layers", "Use near-vertical colliders on these layers as walls."));
            EditorGUILayout.PropertyField(
                ceilingLayers,
                new GUIContent("Ceiling Layers", "Use downward-facing colliders on these layers as ceilings."));

            settings.FindPropertyRelative("placementSurfaceLayers").intValue =
                floorLayers.intValue | wallLayers.intValue | ceilingLayers.intValue;

            SerializedProperty floorThreshold = settings.FindPropertyRelative("floorNormalYThreshold");
            SerializedProperty ceilingThreshold = settings.FindPropertyRelative("ceilingNormalYThreshold");
            float floorAngle = NormalThresholdToAngle(floorThreshold.floatValue);
            float ceilingAngle = NormalThresholdToAngle(ceilingThreshold.floatValue);
            floorAngle = EditorGUILayout.Slider(
                new GUIContent("Maximum Floor Slope", "Steeper surfaces no longer count as floors."),
                floorAngle,
                0f,
                89.9f);
            ceilingAngle = EditorGUILayout.Slider(
                new GUIContent("Maximum Ceiling Slope", "Steeper downward-facing surfaces no longer count as ceilings."),
                ceilingAngle,
                0f,
                89.9f);
            floorThreshold.floatValue = AngleToNormalThreshold(floorAngle);
            ceilingThreshold.floatValue = -AngleToNormalThreshold(ceilingAngle);
        }

        private static void DrawTargetDistribution(SerializedProperty scenario, PlacementTarget targets)
        {
            SerializedProperty modeProperty = scenario.FindPropertyRelative("targetDistributionMode");
            TargetDistributionMode mode = (TargetDistributionMode)modeProperty.intValue;
            int modeIndex = Array.IndexOf(GenerationConfigurationOptions.TargetDistributionModes, mode);
            if (modeIndex < 0)
                modeIndex = 0;

            modeIndex = EditorGui.Popup(
                new GUIContent("Target Distribution", "Choose how the requested count is divided across Floor, Wall, Ceiling, and Inside Space."),
                modeIndex,
                GenerationConfigurationOptions.TargetDistributionLabels);
            mode = GenerationConfigurationOptions.TargetDistributionModes[
                Mathf.Clamp(modeIndex, 0, GenerationConfigurationOptions.TargetDistributionModes.Length - 1)];
            modeProperty.intValue = (int)mode;

            if (mode != TargetDistributionMode.Weighted)
                return;

            SerializedProperty weights = scenario.FindPropertyRelative("targetDistributionWeights");
            int activeWeight = 0;
            activeWeight += DrawTargetWeight(weights, "floor", "Floor Weight", targets, PlacementTarget.Floor);
            activeWeight += DrawTargetWeight(weights, "wall", "Wall Weight", targets, PlacementTarget.Wall);
            activeWeight += DrawTargetWeight(weights, "ceiling", "Ceiling Weight", targets, PlacementTarget.Ceiling);
            activeWeight += DrawTargetWeight(weights, "insideSpace", "Inside Space Weight", targets, PlacementTarget.InsideSpace);

            if (activeWeight <= 0)
                EditorGUILayout.HelpBox("Increase at least one selected target weight.", MessageType.Warning);
        }

        private static int DrawTargetWeight(
            SerializedProperty weights,
            string propertyName,
            string label,
            PlacementTarget targets,
            PlacementTarget target)
        {
            if ((targets & target) == 0)
                return 0;

            SerializedProperty weight = weights.FindPropertyRelative(propertyName);
            weight.intValue = Mathf.Max(0, EditorGUILayout.IntField(
                new GUIContent(label, "Relative share for this target. A weight of zero disables the target while Weighted distribution is active."),
                weight.intValue));
            return weight.intValue;
        }

        private static void DrawRelativePlacement(SerializedProperty relativePlacement)
        {
            SerializedProperty sourceProperty = relativePlacement.FindPropertyRelative("source");
            RelativePlacementSource source = (RelativePlacementSource)sourceProperty.intValue;
            int sourceIndex = Array.IndexOf(BenchmarkRelativeSources, source);
            if (sourceIndex < 0)
                sourceIndex = 0;

            sourceIndex = EditorGui.Popup(
                new GUIContent("Place Near", "Require every placement to stay near an eligible object's bounds."),
                sourceIndex,
                BenchmarkRelativeSourceOptions);
            source = BenchmarkRelativeSources[Mathf.Clamp(sourceIndex, 0, BenchmarkRelativeSources.Length - 1)];
            sourceProperty.intValue = (int)source;

            if (source == RelativePlacementSource.None)
                return;

            SerializedProperty radiusProperty = relativePlacement.FindPropertyRelative("radius");
            radiusProperty.floatValue = Mathf.Max(0.1f, EditorGUILayout.FloatField(
                new GUIContent("Maximum Distance", "Maximum 3D distance from the nearest point on an eligible object's bounds."),
                radiusProperty.floatValue));

            if (source is RelativePlacementSource.SceneObjects or RelativePlacementSource.Any)
            {
                EditorGUILayout.PropertyField(
                    relativePlacement.FindPropertyRelative("sceneLayers"),
                    new GUIContent("Scene Layers", "Only scene objects on these layers may act as relative-placement anchors."));
            }
        }

        private static int GetSelectedTargetCount(PlacementTarget targets)
        {
            int count = 0;
            if ((targets & PlacementTarget.Floor) != 0)
                count++;
            if ((targets & PlacementTarget.Wall) != 0)
                count++;
            if ((targets & PlacementTarget.Ceiling) != 0)
                count++;
            if ((targets & PlacementTarget.InsideSpace) != 0)
                count++;
            return count;
        }

        private static float NormalThresholdToAngle(float threshold) =>
            Mathf.Acos(Mathf.Clamp01(Mathf.Abs(threshold))) * Mathf.Rad2Deg;

        private static float AngleToNormalThreshold(float angleDegrees)
        {
            angleDegrees = Mathf.Clamp(angleDegrees, 0f, 89.9f);
            return Mathf.Max(0f, Mathf.Cos(angleDegrees * Mathf.Deg2Rad));
        }

        private void DrawResults()
        {
            IReadOnlyList<GenerationBenchmarkRunRecord> records = GenerationBenchmarkRunner.RunRecords;

            if (records.Count == 0)
                return;

            EditorGUILayout.Space(5f);
            EditorGUILayout.LabelField("Latest Campaign", EditorStyles.boldLabel);
            int mismatches = records.Count(record =>
                record.measurement == BenchmarkMeasurementKind.Diagnostic.ToString() &&
                record.hasPrimaryReference &&
                !record.resultMatchesPrimary);
            int failures = records.Count(record => !record.succeeded);
            EditorGUILayout.LabelField(
                $"Runs {records.Count:N0} | Failures {failures:N0} | Primary/Diagnostic result mismatches {mismatches:N0}",
                EditorStyles.miniLabel);

            _resultsScroll = EditorGUILayout.BeginScrollView(_resultsScroll, EditorStyles.helpBox, GUILayout.Height(105f));

            foreach (GenerationBenchmarkRunRecord run in records
                         .Skip(Math.Max(0, records.Count - 20))
                         .Reverse())
            {
                EditorGUILayout.LabelField(
                    $"{run.scenario} | {run.cacheCondition} | {run.measurement} | {run.objectCount:N0} | seed {run.seed} | {run.elapsedMilliseconds:0.###} ms | {run.placedCount:N0} placed");
            }

            EditorGUILayout.EndScrollView();
        }

        private void StartBenchmark(bool selectedOnly)
        {
            _serializedSuite.ApplyModifiedProperties();
            _validationMessage = string.Empty;
            GenerationBenchmarkRunner.Start(_suite, selectedOnly ? _selectedScenario : -1);
        }

        private void ValidateSuite()
        {
            _serializedSuite.ApplyModifiedProperties();
            List<string> errors = GenerationBenchmarkRunner.Validate(_suite);
            _validationMessage = errors.Count == 0 ? string.Empty : string.Join("\n", errors);
            _validationMessageType = errors.Count == 0 ? MessageType.None : MessageType.Error;
        }

        private void CreateSuite()
        {
            const string root = "Assets/Genix";
            const string folder = "Assets/Genix/Benchmarks";
            EnsureFolder("Assets", "Genix");
            EnsureFolder(root, "Benchmarks");
            string path = AssetDatabase.GenerateUniqueAssetPath($"{folder}/GenerationBenchmarkSuite.asset");
            GenerationBenchmarkSuite suite = CreateInstance<GenerationBenchmarkSuite>();
            AssetDatabase.CreateAsset(suite, path);
            AssetDatabase.SaveAssets();
            RefreshSelectableAssets();
            SetSuite(suite);
            Selection.activeObject = suite;
        }

        private void SetSuite(GenerationBenchmarkSuite suite)
        {
            _suite = suite;
            _serializedSuite = suite ? new SerializedObject(suite) : null;
            _selectedScenario = 0;

            if (suite)
            {
                string path = AssetDatabase.GetAssetPath(suite);
                EditorPrefs.SetString(SelectedSuiteKey, AssetDatabase.AssetPathToGUID(path));
            }
            else
            {
                EditorPrefs.DeleteKey(SelectedSuiteKey);
            }
        }

        private void RefreshSelectableAssets()
        {
            _benchmarkSuites = AssetDatabase.FindAssets("t:GenerationBenchmarkSuite")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Select(AssetDatabase.LoadAssetAtPath<GenerationBenchmarkSuite>)
                .Where(suite => suite)
                .OrderBy(suite => suite.name, StringComparer.OrdinalIgnoreCase)
                .ToArray();
            _benchmarkSuiteOptions = EditorAssets.CreateAssetOptions(_benchmarkSuites);
            _assetPools = EditorAssets.LoadAssetsFromFolder<AssetPool>(
                ProjectContentPaths.AssetPools,
                (a, b) => string.Compare(a.name, b.name, StringComparison.OrdinalIgnoreCase));
            _assetPoolOptions = EditorAssets.CreateAssetOptions(_assetPools);
            _stylePresets = EditorAssets.LoadAssetsFromFolder<StylePreset>(
                ProjectContentPaths.StylePresets,
                (a, b) => string.Compare(a.name, b.name, StringComparison.OrdinalIgnoreCase));
            _stylePresetOptions = EditorAssets.CreateAssetOptions(_stylePresets);
            Repaint();
        }

        private void HandleProjectChanged()
        {
            RefreshSelectableAssets();

            if (!_suite || !_benchmarkSuites.Contains(_suite))
                SetSuite(_benchmarkSuites.FirstOrDefault());
        }

        private void EnsureSerializedSuite(bool force = false)
        {
            if (force || _serializedSuite == null || _serializedSuite.targetObject != _suite)
                _serializedSuite = new SerializedObject(_suite);
            else
                _serializedSuite.Update();
        }

        private static void EnsureFolder(string parent, string child)
        {
            string path = $"{parent}/{child}";
            if (!AssetDatabase.IsValidFolder(path))
                AssetDatabase.CreateFolder(parent, child);
        }

        private static string FormatDuration(double seconds)
        {
            if (seconds <= 0d)
                return "--";

            TimeSpan duration = TimeSpan.FromSeconds(seconds);
            return duration.TotalHours >= 1d
                ? $"{(int)duration.TotalHours}:{duration.Minutes:00}:{duration.Seconds:00}"
                : $"{duration.Minutes:00}:{duration.Seconds:00}";
        }
    }
}
